package com.laurre.cv.person.experience;

public enum Skill {
    CQRS, DDD, HEXAGONAL_ARCHITECTURE, EMBEDDED_DEVELOPMENT, COMPILER_INTERNALS, SCRUM, TEAM_SELF_ORGANIZATION, ALGORITHMS, DATA_STRUCTURES, CONTINUOUS_IMPROVEMENT, MOBILE_APP_DEVELOPMENT,
}
