package com.laurre.cv.person.experience;

public enum Topic {
    CLEAN_CODE, TEST_DRIVEN_DEVELOPMENT, PAIR_PROGRAMMING, MOB_PROGRAMMING, EXTREME_PROGRAMMING, OPEN_SOURCE, SOFTWARE_DESIGN, CONTINUOUS_INTEGRATION
}
